### PR TITLE
Adding more templates and functions

### PR DESCRIPTION
**Pull request by PedalCore**
I have added more templates and functions, noise, primitives and domain
operators. And added FFT audio analysis and created method for turning audio into a texture file.

### CODE REVIEW

**Comment by hecomi** [comment]
Thanks for the PR!

I saw your codes and thought there were a lot of useful functions, and It would make this plugin more powerful. However, I want to keep all codes and examples simple and clean so that everyone who want to use this plugin can understand what this plugin can do in a short time. The PR includes some unnecessary functions (e.g. `vmax` is same as `max` in HLSL), coding styles are different from the original ones (e.g. indentation, naming convension), and some codes seem to have licenses. 

So, could you separate the PR into small ones that includes only one purpose (ex. *adding primitives*, *adding noise functions*, *adding operators*...) to be able to discuss each function well?

**Comment by PedalCore** [comment]
Hi,

Would you like me to remove the pull request and do individual ones? I can
tidy up and remove a few parts, I included vmax in primitives as a cheap
fix, I think I got an error message about getting to maximum depth of cginc
when using too many references to other cginc files.

I'll take out the code with the license, it's the 2d tiles, it's under
release as general public, I thought it would be useful to tile the out
side of icososphere's.

On the naming convention, I see you are capitalising primitives and
functions, shall everything be capitalised with no reference to it's type,
ie maybe domain operations end with Op to denote an operation, anything
else on the naming convention other than every function starts with a
capital? Does is matter to you about using p or pos for the input of the
distance function?

**Comment by hecomi** [comment]
Actually, at this point, I think it might be a good idea for you to improve this plugin in your branch. Because I have a plan to separate some functions into different plugins, for example, the code editor with syntax highlighting, shader template system, and uRaymarching using them as subsystems. Regarding uRaymarching itself, I think it's a little big now, so I'd like to move primitives, fractales, and simple operators into the example layer to keep the library layer simple and extensible so that everyone can write raymarching codes in their own way.

**Comment by PedalCore** [comment]
Ok that's a good idea, are you separating the repository up into smaller
individual components? I'll carry on improving for myself, I still think
colouring needs to be addressed I've got audio controlling the distance
function, so I'm happy! https://www.youtube.com/watch?v=_1e6gZ9q6C4

**Comment by pechaut** [comment]
Hi Hecomi, your plugin is awesome !

I guess we will all need, at one point, to customize the standard functions, and it is probably a bad idea to directly modify the provided files.

So maybe, just like the "Properties" or "Post Effect" tab, a new tab could propose to add some additionnable custom cginc files ? (that could be shared among different materials)

What do you think ?

**Comment by hecomi** [comment]
@pechaut 
Thanks for the comment! I opened new issue related to your question #6.

@richhop 
Sorry for my super late reply..., yes, I have a plan to separate the current asset into some small components but I've not done it yet because I'm now working on an another project... So I would be glad if you wait for that time.

**Pull request closed without merging**
